name: dynamic_fontstyle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/icon.png"
  web:
    generate: true
    image_path: "lib/icon.png"
  windows:
    generate: true
    image_path: "lib/icon.png"
  macos:
    generate: true
    image_path: "lib/icon.png"