name: english_dictionary
description: "Easy User Friendly English Dictionary App"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.0
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "lib/app_icon.jpg"
  android: true
  ios: true